spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
       routes:
         - id: microservicio
           uri: lb://MICROSERVICIO
           predicates:
             - Path=/pelicula/**
server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

