spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
       routes:
         - id: microservicio
           uri: lb://MICROSERVICIO
           predicates:
             - Path=/pelicula/**
           filters:
             - name: CircuitBreaker
               args:
                 name: microservicio
                 fallbackuri: forward:/peliculaFallBack
server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

managment:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000